"""steameditor.core — Core processing package."""

from steameditor.core.models import (
    Template,
    MultiPart,
    EffectConfig,
    BorderFXConfig,
    TextOverlayConfig,
    AutoEnhanceConfig,
    OutputConfig,
    SteamConfig,
    AppConfig,
    Profile,
    Project,
    ProcessingContext,
    ProcessingResult,
    BUILTIN_TEMPLATES,
    DEFAULT_TEMPLATE,
    uniform_slice_bounds,
)
from steameditor.core.processor import (
    process_image,
    split_gif_frames,
    process_folder,
    manual_crop_with_template,
    apply_effects_pipeline,
    _apply_effects_pipeline,
    apply_border_fx,
    apply_text_overlay,
    apply_auto_enhance,
    resize_cover,
    autocrop_borders,
    save_output_piece,
    patch_png_last_byte,
    patch_gif_trailing_byte,
    optimize_gif_file,
    list_border_templates,
    find_gifsicle,
    render_template_preview,
    template_output_summary,
    render_showcase_preview,
    open_folder,
    text_overlay_bbox,
)
from steameditor.core.uploader import run_upload, UploadError
from steameditor.core.template_matcher import (
    TemplateMatcher,
    TemplateMatch,
    get_template_matcher,
)

__all__ = [
    # Models
    "Template",
    "MultiPart",
    "EffectConfig",
    "BorderFXConfig",
    "TextOverlayConfig",
    "AutoEnhanceConfig",
    "OutputConfig",
    "SteamConfig",
    "AppConfig",
    "Profile",
    "Project",
    "ProcessingContext",
    "ProcessingResult",
    "BUILTIN_TEMPLATES",
    "DEFAULT_TEMPLATE",
    "uniform_slice_bounds",
    # Processor
    "process_image",
    "split_gif_frames",
    "process_folder",
    "manual_crop_with_template",
    "apply_effects_pipeline",
    "_apply_effects_pipeline",
    "apply_border_fx",
    "apply_text_overlay",
    "apply_auto_enhance",
    "resize_cover",
    "autocrop_borders",
    "save_output_piece",
    "patch_png_last_byte",
    "patch_gif_trailing_byte",
    "optimize_gif_file",
    "list_border_templates",
    "find_gifsicle",
    "render_template_preview",
    "template_output_summary",
    "render_showcase_preview",
    "open_folder",
    "text_overlay_bbox",
    # Template Matcher
    "TemplateMatcher",
    "TemplateMatch",
    "get_template_matcher",
    # Uploader
    "run_upload",
    "UploadError",
]